- config.toml
- content/general-guidance.md
- content/implementation-path.md
- layouts/_default/single.html
- layouts/partials/docs/content.html
> Add general guidance, refine single.html

- assets/sass/custom.sass
- config.toml
- content/word-list.md
> Add recommendations, refine header typography

- config.toml
- content/evaluation-framework.md
> Add wg naming language evaluation framework

- config.toml
> Reorder lefthand menu

- config.toml
- content/_index.md
- content/related-projects.md
- layouts/shortcodes/button.html
> Move related projects to subpage

- content/_index.md
> Use a different summary

- layouts/shortcodes/jumbotron.html
> Remove jumbotron corner radius

- content/_index.md
> Change time

- content/about.md
> Red Hat, not RedHat

- content/_index.md
- layouts/shortcodes/cta.html
> Update homepage CTA to no longer mention kubecon

- content/about.md
- layouts/partials/home/hero.html
As per #40 fixes 'get-involved' links.
> Fix get-involved link

- content/language/word-list.md
As per https://groups.google.com/u/1/g/inclusivenaming/c/Uu8VKrwblgk
Signed-off by: Karsten Wade <quaid@iquaid.org>
> Fixing to canonical link, rather than versioned

- content/related-projects.md
As per https://groups.google.com/u/1/g/inclusivenaming/c/Uu8VKrwblgk
Signed-off by:  Karsten Wade <quaid@iquaid.org>
> Updating to canonical link from versioned one

- layouts/shortcodes/leadership.html
ref: https://twitter.com/stephenaugustus/status/1381695422113144838
Signed-off-by: Stephen Augustus <foo@auggie.dev>
> Update Stephen Augustus' affiliation

- content/workstreams.md
Mailing list announcement: https://groups.google.com/g/inclusivenaming/c/J4xGn6ShnJs
Signed-off-by: Stephen Augustus <foo@auggie.dev>
cc: @ddavisjones @jasonbrooks @celestehorgan
> workstreams: Merge OSS and Community + Tooling, add new leads

- config.toml
- content/participate.md
Signed-off-by: gkarthiks <github.gkarthiks@gmail.com>
Adds YouTube link to the site and fixes a case issue in the string LinkedIn
Fixes: #28
> add: youtube link #28 and fix casing in LinkedIn

- config.toml
- content/code-of-conduct.md
> add empty code of conduct page

- content/code-of-conduct.md
Update code of conduct webpage to include Committee description & membership, as well as "How to Report a Violation"
> Update code of conduct webpage

- content/about.md
I'm submitting proposed changes to the mission statement and other contents of the About Us webpage per recent discussion among the leads
> Update About Us webpage

- layouts/shortcodes/logos.html
> Fix SDDI URL as per #69

- layouts/_default/_markup/render-heading.html
> re-add anchor links to subpages

- content/language/evaluation-framework.md
- content/language/implementation-path.md
- content/outreach.md
- content/participate.md
- layouts/shortcodes/logos.html
These changes are to address https://github.com/inclusivenaming/org/issues/44 and https://github.com/inclusivenaming/org/issues/45, and discuss how to make changes (methodically, carefully, patiently) on your own project, as well as how to approach another projects (patiently, tactfully, compassionately) for best results, without making people feel defensive, or feel attacked.
> Recommendations and best practices for language changes

- content/language/evaluation-framework.md
This adds a second revision of the language evaluation framework, as worked on by the Language workstream. Big shoutout to @joannalee333 for her hard work on this with me!
> Add language evaluation framework 2.0

- static/json/dci-lint-config-recommended-v1.json
The contents are derived from the recommendations
of the INI and are a direct translation of those
into JSON with a specific schema that DCI Lint expects.
Signed-off-by: Peter Somogyvari <peter.somogyvari@accenture.com>
> Add machine parsable DCI Lint configuration

- .gitignore
- content/_index.md
- content/participate.md
- layouts/partials/javascript.html
- layouts/shortcodes/localize.html
- package.json
Signed-off-by: Ed Warnicke <hagbard@gmail.com>
> Fix time to display in local tz of viewer

- content/related-projects.md
> revise ibm wording

- static/_redirects
Fixes #111 
(I missed this in review for https://github.com/inclusivenaming/website/pull/112)
Signed-off-by: Stephen Augustus <foo@auggie.dev>
> static: Update `/language/word-list` redirect

- config.toml
- content/word-lists/tier-3.md
> Add segregate recommendation

- layouts/shortcodes/leadership.html
> add jason brooks to leads page

- .github/CODEOWNERS
- .github/settings.yml
Signed-off-by: Stephen Augustus <foo@auggie.dev>
> .github: Add initial CODEOWNERS and settings.yml config

- layouts/shortcodes/logos.html
Signed-off-by: Abubakar Siddiq Ango <hello@abuango.me>
> Change Members to Sponsors in Logos Section

- content/word-lists/tier-3.md
This adds the Tribe recommendation to Tier 3 of the language list.
> Add tribe recommendation to Tier 3

- config.toml
- content/word-lists/no-change.md
> Add no changes recommended list

- assets/sass/custom.sass
- config.toml
- content/about.md
- content/sponsor.md
@taylorwaggoner Kindly review new updates and here is a rendering of the new sponsorship page:
> Created Sponsorship Page 

- assets/sass/custom.sass
- content/word-lists/no-change/blackbox.md
- content/word-lists/no-change/whitebox.md
- content/word-lists/no-change/whitelabel.md
> Add white box and white label

- content/language/word-list/cripple.md
- Putting this with other terms as an individual file.
- Location may not be the final home, we need to sort out as the Language WS how
the site layout works.
> Adding term "cripple" for tier 1 list

- content/related-projects.md
https://groups.google.com/g/kubernetes-wg-naming/c/e_F2r4y9xls
> remove Kubernetes as the group seems to have been dissolved

- content/word-lists/tier-3/hallucinate.md
- generateDocFormats.sh
- layouts/wordlist/list.json.json
- layouts/wordlist/section.html
- netlify.toml
PR fixes:
- Bug in JSON export
- Hallucinate term page
- Implement PDF exports
> Fix JSON, Hallucinate term bugs and implement PDF exports

- content/word-lists/tier-3/evangelist.md
Recommend adding "evangelist" (tier 3)
> Adding term "evangelist" to tier-3

- content/word-lists/tier-3/blast-radius.md
Recommendation for blast radius (tier 3)
> Adding term "blast radius" to tier-3

- content/word-lists/tier-3/man-hour.md
Many business applications work with time estimates for which the term man-hour is used. This term is easily replaced by more inclusive-terms.
> Adding term "man-hour" to tier-3

- content/word-lists/tier-3/evangelist.md
fixes: https://github.com/inclusivenaming/website/issues/171
[Deploy preview](https://deploy-preview-175--inclusivenaming.netlify.app/word-lists/tier-3/evangelist/)
> updating formatting of Evangelist page to adhere to word template
